### ISSUE TITLE
[Bug] Checking if all threads are finished when using multi-processors. 

### ISSUE THREAD

**Issue by ancaandrei** [Morpho-lang/morpho#226] opened 2023-05-31 19:54 UTC
**Describe the bug**
When using multiple processes, say with -w4, the code does not check if all threads are complete. 

**To Reproduce**
1. run morpho5 -w4 filename.morpho
2. Check result
3. run step 1 again, without clearing anything
4. Check result
5. Notice the results are different. 

**Expected behavior**
We expect steps 2 and 4 to be the same.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by softmattertheory** [comment] 2023-06-02 23:09
Thanks for this @ancaandrei! We've reproduced the bug, and it appears to actually be caused by the unsafe linearize() method on the Field class rather than threads not completing. This is fixed by #225 and will work in the next release. Thanks for bringing this to our attention!

**Closed by softmattertheory** 2023-06-02 23:09 UTC
Labels: bug
